export { sceneStore } from '@/engine/scene-store'
export { DEFAULT_ENVIRONMENT, ENVIRONMENT_LIMITS } from '@/engine/model/environment'
export type { Environment } from '@/engine/model/environment'
export type { Project } from '@/engine/model/project'
export type { Element, ElementChanges, SquareElement, TextElement } from '@/engine/model/element'
export { createSquareElement, createTextElement } from '@/engine/model/element-factory'
export { resolveCoveringElement } from '@/engine/coverage'
